language: objective-c
osx_image: xcode9
install:
- brew update
- brew install cocoapods
- pod update
- pod install
script:
- xcodebuild -workspace Funkey.xcworkspace -scheme "1MoreKey" build CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO | xcpretty
before_deploy:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/developerID.cer.enc
  -d -a -out scripts/certs/developerID.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/developerID.p12.enc
  -d -a -out scripts/certs/developerID.p12
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dsa_priv.pem.enc -d
  -a -out scripts/certs/dsa_priv.pem
- "./scripts/add-key.sh"
deploy:
  provider: script
  script: scripts/release_app
  skip_cleanup: true
  on:
    repo: jackymelb/1MoreKey
    tags: true
after_deploy:
- "./scripts/remove-key.sh"